FROM nginx:1.23.3

ENV NGINX_VERSION "1.23.3"
ENV NJS_VERSION   0.7.10

# We modify the nginx base image by:
# 1. Replacing the entrypoint script with a modified version that explicitly
#    sets resolvers.
# 2. Explicitly install the version of njs coded in the environment variable
#    above.

COPY ./build_context/etc /etc

RUN set -eux \
    export DEBIAN_FRONTEND=noninteractive; \
    # mkdir -p /var/cache/nginx/s3_proxy; \
    # chown nginx:nginx /var/cache/nginx/s3_proxy; \
    chmod -R -v +x /docker-entrypoint.sh /docker-entrypoint.d/*.sh; \
    echo "deb https://nginx.org/packages/mainline/debian/ $(echo $PKG_RELEASE | cut -f2 -d~) nginx" >> /etc/apt/sources.list.d/nginx.list; \
    apt-get update; \
    apt-get install --no-install-recommends --no-install-suggests --yes \
      curl nginx-module-njs=${NGINX_VERSION}+${NJS_VERSION}-${PKG_RELEASE}; \
    apt-get remove --purge --auto-remove --yes; \
    rm -rf /var/lib/apt/lists/* /etc/apt/sources.list.d/nginx.list

